# Generated by Django 4.0.3 on 2022-04-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('receiver', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=256)),
            ],
        ),
    ]
