# Generated by Django 4.0.3 on 2022-04-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_hassend_draftbox_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='APMI',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
