# Generated by Django 4.0.3 on 2022-04-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0004_users_apmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbox',
            name='sender',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
