# Generated by Django 4.0.3 on 2022-04-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_draftbox_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='username_verifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifyCode', models.CharField(max_length=8)),
            ],
        ),
    ]
