# Generated by Django 4.0.3 on 2022-04-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0006_username_verifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='username_verifycode',
            name='username',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
