# Generated by Django 4.0.3 on 2022-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0007_username_verifycode_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('loginTime', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
    ]
