# Generated by Django 4.0.3 on 2022-04-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0009_alter_token_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='APMI',
            new_name='IMAP',
        ),
    ]
