# Generated by Django 4.0.3 on 2022-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0010_rename_apmi_users_imap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftbox',
            name='content',
            field=models.CharField(max_length=2560),
        ),
        migrations.AlterField(
            model_name='hassend',
            name='content',
            field=models.CharField(max_length=2560),
        ),
    ]
